{{- if .Values.global.ui.install }}
{{- if .Values.global.ui.ingressenabled }}
{{- $fullName := include "openidl-ui.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: ui-ingress
  labels:
    {{- include "openidl-ui.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ui.ingressenabled }}
  tls:
  - hosts:
    - {{ .Values.global.ui.ingresshostname }}
    secretName: ui-tls
  {{- end }}
  ingressClassName: {{ .Values.global.ui.ingressClassName }}
  rules:
    - host: {{ .Values.global.ui.ingresshostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.ui.servicename }}
                port: 
                  number: {{ .Values.global.ui.port }}
  {{- end }}
{{- end }}

