ordererorg_domain: "thetech.digital"
domain: "thetech.digital"
internal_domain: "internal.thetech.digital"
node_type: "aais"
network:
  org_name: "aais"
  ordererorg: "true"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "analytics"
      domain: "analytics.thetech.digital"
    - name: "carrier"
      domain: "carrier.thetech.digital"
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: develop-nd
      repo_path: openidl-chaincode/chaincode/openidl
  - name: anal-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: develop-nd
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
