ordererorg_domain: "aais.uim.openidl.org"
domain: "ca09.uim.openidl.org"
internal_domain: "ca09.internal.uim.openidl.org"
node_type: "carrier"
network:
  org_name: "ca09"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: ""
      domain: ""
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
  - name: anal-ca09
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_ca09_pdc"
          policy: "OR('analyticsMSP.member', 'ca09MSP.member')"
