ordererorg_domain: "thetech.digital"
domain: "cnd.thetech.digital"
internal_domain: "cnd.internal.thetech.digital"
node_type: "carrier"
network:
  org_name: "cnd"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "analytics"
      domain: "analytics.thetech.digital"
    - name: "cnd"
      domain: "cnd.thetech.digital"
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
  - name: anal-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: anal-cnd
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_cnd_pdc"
          policy: "OR('analyticsMSP.member', 'cndMSP.member')"
