global:
    clusterurl: cnd.thetech.digital
    appsecret: apps-secret
    configpath: config-cnd
    datacallapp:
        install: true
        port: 8080
        targetport: 8080
        servicename: data-call-app-service
        ingressenabled: true
        ingresshostname: data-call-app-service.dev.cnd.internal.thetech.digital
        publicingresshostname: data-call-app-service.dev.cnd.thetech.digital
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-data-call-app
            pullPolicy: IfNotPresent
            tag: 19-npm-error-9b6d860-110820222048
    utilities:
        install: true
        port: 8080
        targetport: 8080
        servicename: utilities-service
        ingressenabled: true
        ingresshostname: utilities-service.dev.cnd.internal.thetech.digital
        publicingresshostname: utilities-service.dev.cnd.thetech.digital
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-utilities
            pullPolicy: IfNotPresent
            tag: 27-npm-error-9b6d860-110820222100
    carrierui:
        install: true
        servicename: cnd-ui-service
        port: 8080
        targetport: 8080
        ingressenabled: true
        ingresshostname: openidl.dev.cnd.thetech.digital
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-carrier-ui
            pullPolicy: IfNotPresent
            tag: 31-npm-error-9b6d860-110820222049
    insurancedatamanager:
        install: true
        port: 8080
        targetport: 8080
        servicename: insurance-data-manager-service
        ingressenabled: true
        ingresshostname: insurance-data-manager-service.dev.cnd.thetech.digital
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-insurance-data-manager
            pullPolicy: IfNotPresent
            tag: 24-npm-error-9b6d860-110820222049
    datacallprocessor:
        install: true
        port: 8080
        targetport: 8080
        servicename: data-call-processor-service
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-data-call-processor
            pullPolicy: IfNotPresent
            tag: 18-npm-error-9b6d860-110820222049
    upload:
        install: true
        port: 80
        targetport: 80
        servicename: upload-service
        image:
            repository: ghcr.io/openidl-org/openidl-upload
            pullPolicy: IfNotPresent
            tag: latest
    datacallmoodlistener:
        install: false
        port: 8080
        targetport: 8080
        servicename: data-call-mood-listener-service
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-data-call-mood-listener
            pullPolicy: IfNotPresent
            tag: 15-npm-error-9b6d860-110820222048
    transactionaldataeventlistener:
        install: false
        port: 8080
        targetport: 8080
        servicename: transactional-data-event-listener-service
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-transactional-data-event-listener
            pullPolicy: IfNotPresent
            tag: 15-npm-error-9b6d860-110820222049
    ui:
        install: false
        servicename: ui-service
        port: 8080
        targetport: 8080
        ingressenabled: false
        ingresshostname: openidl.dev.cnd.thetech.digital
        image:
            repository: ghcr.io/openidl-org/openidl-main/openidl-org/openidl-ui
            pullPolicy: IfNotPresent
            tag: 31-npm-error-9b6d860-110820222049
    secrets:
        install: true