- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - include_role:
        name: "import-config-vars"
    - set_fact:
        switch_to_cluster: "{{openidl_apps_cluster}}"
    - include_role:
        name: "setup/switch-cluster"
    - include_role:
        name: "openidl-config"
    - include_role:
        name: "openidl-secrets"
