# Usage:
#   ansible-playbook role_nginx_ingress.yml -e do=create -e cluster=app-cluster -e type=external
#   ansible-playbook role_nginx_ingress.yml -e do=delete -e cluster=app-cluster -e type=external
#
# VARS:
#   cluster= [app-cluster/blk-cluster] - default: app-cluster
#   type= [external/internal] - default: external
---
- name: Nginx Ingress Controller
  hosts: ansible_provisioners
  gather_facts: no
  vars:
    do: create
    wait_timeout: 3600
  
  tasks:
    - include_role:
        name: "import-config-vars"
    - set_fact:
        switch_to_cluster: "{{openidl_apps_cluster}}"
    - include_role:
        name: "setup/switch-cluster"
    - set_fact:
        nginx_cluster: "{{openidl_apps_cluster}}"
    - include_role:
        name: "nginx-ingress"

