- hosts: ansible_provisioners
  gather_facts: no
  tasks:
    - include_role:
        name: "import-config-vars"
    - set_fact:
        switch_to_cluster: "{{openidl_apps_cluster}}"
    - include_role:
        name: "setup/switch-cluster"
    - name: "Blockchain collection"
      include_role:
        name: setup/blockchain-platform
      vars:
        blockchain_collection_install: true
    - set_fact:
        apps_config_reader_name: "k8s-secret"
    - include_role:
        name: "openidl-config"
    - include_role:
        name: "openidl-secrets"
