#
# SPDX-License-Identifier: Apache-2.0
#
# Usage:
# Create: ansible-playbook role_fabric_operator.yml --extra-vars "state=present"
# Delete: ansible-playbook role_fabric_operator.yml --extra-vars "state=absent"
---
- name: Deploy Opensource custom resource definitions and operator
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    state: present
    wait_timeout: 3600
  roles:
    - role: fabric-operator
